import { Inter } from "next/font/google";
import "./globals.css";
import { TimeContextProvider } from "./provider";
import { getTime } from '@/lib/getTime';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await getTime();
  return (
    <html lang="en">
      <TimeContextProvider value={data}>
          <body className={inter.className}>

          {children}
          </body>
      </TimeContextProvider>
    </html>
  );
}
